version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install"

  build:
    commands:
      - echo "Build phase: nothing to compile for static HTML/JS"

artifacts:
  files:
    - '**/*'
  base-directory: '.'
